# ================================
#  admin-service (NestJS) — DÉVELOPPEMENT (hot-reload)
# ================================
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate --schema src/infrastructure/database/prisma/schema.prisma
EXPOSE 3001
ENV PORT=3001
# Pousse le schéma vers la base puis lance NestJS en watch
CMD ["sh", "-c", "npx prisma db push --schema src/infrastructure/database/prisma/schema.prisma && npm run start:dev"]
