FROM node:20-alpine

WORKDIR /app

# Installer pnpm
RUN npm install -g pnpm

# Copier uniquement les fichiers de dépendances
COPY package*.json pnpm-lock.yaml ./

# Installer les dépendances dans l'image
RUN pnpm install

# Copier le reste du code (sans node_modules grâce à .dockerignore)
COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]