/** Codes d'erreur métier du domaine. */
export enum DomainErrorCode {
  ANIMAL_ALREADY_ENROLLED = 'ANIMAL_ALREADY_ENROLLED',
  ANIMAL_NOT_FOUND = 'ANIMAL_NOT_FOUND',
  ELEVEUR_NOT_FOUND = 'ELEVEUR_NOT_FOUND',
  AGRICULTEUR_NOT_FOUND = 'AGRICULTEUR_NOT_FOUND',
  UNAUTHORIZED_ENROLLMENT = 'UNAUTHORIZED_ENROLLMENT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  CAMPAIGN_INVALID = 'CAMPAIGN_INVALID',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
